  site_name: Contract Docs
  nav:
    - Home: 'index.md'
    - User: 
      - Main: './user/user.md'
    - Contract: 
      - 合同: './contract/index.md'    
     
    - 管理后台: 
      - 用户: './admin/user.md'    
      
      
